version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:7.0

    steps:
      - checkout

      - restore_dependencies:
          name: Restore Dependencies
          command: dotnet restore

      - build_project:
          name: Build
          command: dotnet build $lib

  test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:7.0

    steps:
      - checkout

      - restore_dependencies:
          name: Restore Dependencies
          command: dotnet restore

      - run_tests:
          name: Test
          command: dotnet test

  release:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:7.0

    steps:
      - checkout

      - restore_dependencies:
          name: Restore Dependencies
          command: dotnet restore

      - install_gitversion:
          name: Install GitVersion
          command: dotnet tool install --global gitversion.tool
          environment:
            PATH: ~/.dotnet/tools

      - get_version:
          name: Get Version
          command: |
            SEMVER=$(dotnet-gitversion /showvariable SemVer)
            NEXTVER=$(dotnet-gitversion /showvariable MajorMinorPatch)
            echo "Current branch semver is '$SEMVER'"
            echo "Main branch candidate semver is '$NEXTVER'"

  deploy_nuget:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:7.0

    steps:
      - checkout

      - restore_dependencies:
          name: Restore Dependencies
          command: dotnet restore

      - install_gitversion:
          name: Install GitVersion
          command: dotnet tool install --global gitversion.tool
          environment:
            PATH: ~/.dotnet/tools

      - get_version:
          name: Get Version
          command: |
            SEMVER=$(dotnet-gitversion /showvariable SemVer)
            echo "Releasing version $SEMVER"

      - build_and_pack:
          name: Build and Pack
          command: |
            dotnet-gitversion /updateprojectfiles
            rm -f bin/Debug/*.nupkg
            dotnet pack
            dotnet nuget push bin/Debug/*.nupkg -s https://api.nuget.org/v3/index.json -k $nuget_api_key

      - push_changes:
          name: Push Changes
          command: |
            git push -o ci.skip
            git push --tags
